# Generated by Django 6.0 on 2025-12-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(choices=[('MCA', 'MCA'), ('MMS', 'MMS')], max_length=10)),
                ('semester', models.IntegerField()),
                ('password', models.CharField(default='sies@123', max_length=100)),
            ],
        ),
    ]
