# Generated by Django 6.0 on 2025-12-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
